spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://localhost:3316/sswm
    username: root
    password: ssjjmt206
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        format_sql: true
        show_sql: true
    servlet:
      multipart:  # 파일 올리는 설정
        max-file-size: 50MB # 요청한 파일 한 개의 크기
        max-request-size: 50MB # 요청한 파일 전체의 크기
  redis:
    host: localhost
    port: 6379
    password: root

# jwt 설정
custom:
  jwt:
    secret: jwt시크릿

# S3 사용 설정
cloud:
  aws:
    credentials:
      accessKey: AKIAZPPUJPXAEPPKBU4Z       # AWS IAM AccessKey 적기
      secretKey: 3Kgaf4A2pddtxT6bfH8Nr8pcsCT5OsoOjfQt/E/w   # AWS IAM SecretKey 적기
    s3:
      bucket: sswm-image
    region:
      static: ap-northeast-2
    stack:
      auto: false
# auth 사용 설정
auth:
  google:
    client-id: 508793857526-hjnar37f3fdnjsopr7lv7dfgkf972p5h.apps.googleusercontent.com
    client-secret: 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
    scope:
      - email
      - profile
    token-req-url : https://oauth2.googleapis.com
  kakao:
    client-id: a8cdfb7c6e1ce33857c1ff4df66c348c
    client-secret: ViVXmJMU0xE6pgqJOTmdc8drLdj3n5BV
    scope:
      - profile_nickname
      - profile_image
      - account_email
  redirect-url: http://localhost:3000

logging:
  level:
    com.ground.sswm : DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

server:
  servlet:
    context-path: /api
  port:
    8080

